service:
  name: htmlToScreenshot

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  memorySize: 1536
  timeout: 180
  # if needed (e.g. upload snapshot)
  # iamRoleStatements:
  #  -  Effect: "Allow"
  #     Action:
  #       - "s3:PutObject"
  #     Resource: "arn:aws:s3:::<bucket name>/*"

# Add the serverless-webpack plugin
plugins:
  - serverless-apigw-binary
  - serverless-s3-local
  - serverless-webpack
  - serverless-offline
custom:
  apigwBinary:
    types:
      - 'image/png'
# Uncomment only if you want to collaborate with serverless-plugin-additional-stacks
# additionalStacks:
#    permanent:
#      Resources:
#        S3BucketData:
#            Type: AWS::S3::Bucket
#            Properties:
#                BucketName: ${self:service}-data
  s3:
    host: 0.0.0.0
    port: 8000
    directory: /tmp
    # Uncomment the first line only if you want to use cors with specified policy
    # Uncomment the second line only if you don't want to use cors
    # Not uncomment the these lines only if your wanto use cors with default policy
    # cors: relative/path/to/your/cors/policy/xml
    # cors: false
    # Uncomment only if you already have a S3 server running locally
    # noStart: true
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: local-bucket
functions:
  api:
    handler: src/api/api.handler
    events:
      - http:
          method: post
          path: screenshot.png
